<?php

/**
 * Implementation of hook_ctools_plugin_api().
 */
function teambuilder_activities_ctools_plugin_api() {
  list($module, $api) = func_get_args();
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => 1);
  }
}

/**
 * Implementation of hook_imagecache_default_presets().
 */
function teambuilder_activities_imagecache_default_presets() {
  $items = array(
    'activity' => array(
      'presetname' => 'activity',
      'actions' => array(
        '0' => array(
          'weight' => '0',
          'module' => 'imagecache',
          'action' => 'imagecache_scale',
          'data' => array(
            'width' => '400',
            'height' => '400',
            'upscale' => 0,
          ),
        ),
      ),
    ),
  );
  return $items;
}

/**
 * Implementation of hook_node_info().
 */
function teambuilder_activities_node_info() {
  $items = array(
    'activity' => array(
      'name' => t('Aktivitet'),
      'module' => 'features',
      'description' => '',
      'has_title' => '1',
      'title_label' => t('Titel'),
      'has_body' => '1',
      'body_label' => t('Brødtekst'),
      'min_word_count' => '0',
      'help' => '',
    ),
  );
  return $items;
}

/**
 * Implementation of hook_views_api().
 */
function teambuilder_activities_views_api() {
  return array(
    'api' => '2',
  );
}
