<?php
require_once 'fpdf.php';

/**
 * Implementation of hook_menu()
 */ 
function teambuilder_activities_pdf_menu() {
    $items['node/%node/pdf'] = array(
        'title' => 'PDF',
        'page callback' => 'exercise_pdf_portrait',
        'page arguments' => array(1),
        'type' => MENU_LOCAL_TASK,
        'access callback' => 'exercise_pdf_access',
        'access arguments' => array(1)
    );
    return $items;
}

function exercise_pdf_access($node) {
    if ($node->type != 'activity') {
        return false;
    }
    return true;
}

/**
 * Creates a pdf of an exercise node
 * 
 * @param $nid Node id
 *
 * @return void
 */
function exercise_pdf_portrait($node) {
    global $base_url;
    require_once 'fpdf.php';

    $title = "  " . utf8_decode($node->title);
    $description = utf8_decode(strip_tags($node->field_instruction[0]['value']));
    $keywords = array();
    foreach ($node->taxonomy as $taxonomy) {
        $keywords[] = $taxonomy->name;
    }

    $url = $base_url. '/node/' . $node->nid;

    $pdf = new FPDF('P','mm','A4');
    $pdf->SetTitle($title);
    $pdf->SetSubject($title);
    $pdf->SetAuthor('Motionsplan.dk');
    $pdf->SetAutoPageBreak(false);
    $pdf->SetMargins(0, 0, 0);    

    $pdf->AddPage();

    $title_size = 30;

    $pdf->SetFont('Helvetica', 'B', $title_size);

    $title_width = $pdf->GetStringWidth($title);
    
    if ($title_width > 200) {
        $title_size = 25;
    }
    
    $pdf->SetFont('Helvetica', 'B', $title_size);

    $pdf->SetFont('Helvetica', 'B', $title_size);
    $pdf->SetTextColor(255, 255, 255);
    $pdf->Cell(0, 50, $title, null, 2, 'L', true);
    
    $pdf->SetLeftMargin(10);
    $pdf->SetRightMargin(10);
    $pdf->SetY(35);
    $pdf->SetFont('Helvetica', null, 10);
    $pdf->MultiCell(0, 5, utf8_decode(implode($keywords, ", ")), 0, 'L');

    if (!empty($node->field_image)) {
        $x = 10;
        $y = 60;
        $width = 0;
        $spacing = 5;
        $count = 0;
        $picture_rows = 1;
        foreach ($node->field_image as $image) {
            $file = realpath(dirname(__FILE__) . '/../../../../../' . $image['filepath']);
            $size = getimagesize($file);
            if ($size[0] < $size[1]) {
                $orientation = 'portrait';
                $pic_width = 55;
                $new_line = 80;
                if ($count > 6) {
                    break;
                }
            } else {
                $orientation = 'landscape';
                $pic_width = 80;
                $new_line = 50;
                if ($count > 4) {
                    break;
                }
            }
            $width += $pic_width + $spacing;

            if ($width > 200) {
                $y += $new_line;
                $x = 10;
                $picture_rows++;
                $width = 0;
            }

            $pdf->Image($file,$x,$y,$pic_width,0,'');
            $x += $pic_width + $spacing;
        }
    }

    $pdf->SetFont('Helvetica', null, 17);
    $pdf->setTextColor(0, 0, 0);

    if ($orientation == 'portrait') {
        if ($picture_rows == 1) {
            $pdf->setY(150);
        } else {
            $pdf->setY(230);
        }
    } else {
        if ($picture_rows == 1) {
            $pdf->setY(130);
        } else {
            $pdf->setY(200);
        }
    }

    $pdf->MultiCell(0, 8, $description, 0);

    $pdf->Image(dirname(__FILE__) . '/vih_logo.jpg',8,261,50,0,'', 'http://vih.dk/');
    $pdf->Image(dirname(__FILE__) . '/cc-by-sa_340x340.png',190,3,17,0,'');

    $pdf->SetFont('Helvetica', null, 8);
    $pdf->setY(280);
    $pdf->setX(7);
    $pdf->MultiCell(50, 8, $url, 0, 'C');

    $image_url = "http://chart.apis.google.com/chart?cht=qr&chs=100x100&chl=" . $url;
  
    $ch = curl_init();
    $timeout = 0;
    curl_setopt ($ch, CURLOPT_URL, $image_url);
    curl_setopt ($ch, CURLOPT_CONNECTTIMEOUT, $timeout);

    // Getting binary data
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_BINARYTRANSFER, 1);

    $image = curl_exec($ch);

    curl_close($ch);

    $f = fopen(dirname(__FILE__) . '/barcodes/'. md5(request_uri()) . '.png', 'w');
    fwrite($f, $image);
    fclose($f);

    $pdf->Image(dirname(__FILE__) . '/barcodes/' . md5(request_uri()) . '.png', 160, 245, 45, 0, '');

    $pdf->Output();
}

